/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 1;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _CRT_FUNCTIONS_REQUIRED: u32 = 1;
pub const _CRT_HAS_CXX17: u32 = 0;
pub const _CRT_HAS_C11: u32 = 1;
pub const _CRT_INTERNAL_NONSTDC_NAMES: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const _STATIC_INLINE_UCRT_FUNCTIONS: u32 = 1;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const PRId8: &[u8; 4] = b"hhd\0";
pub const PRId16: &[u8; 3] = b"hd\0";
pub const PRId32: &[u8; 2] = b"d\0";
pub const PRId64: &[u8; 4] = b"lld\0";
pub const PRIdLEAST8: &[u8; 4] = b"hhd\0";
pub const PRIdLEAST16: &[u8; 3] = b"hd\0";
pub const PRIdLEAST32: &[u8; 2] = b"d\0";
pub const PRIdLEAST64: &[u8; 4] = b"lld\0";
pub const PRIdFAST8: &[u8; 4] = b"hhd\0";
pub const PRIdFAST16: &[u8; 2] = b"d\0";
pub const PRIdFAST32: &[u8; 2] = b"d\0";
pub const PRIdFAST64: &[u8; 4] = b"lld\0";
pub const PRIdMAX: &[u8; 4] = b"lld\0";
pub const PRIdPTR: &[u8; 4] = b"lld\0";
pub const PRIi8: &[u8; 4] = b"hhi\0";
pub const PRIi16: &[u8; 3] = b"hi\0";
pub const PRIi32: &[u8; 2] = b"i\0";
pub const PRIi64: &[u8; 4] = b"lli\0";
pub const PRIiLEAST8: &[u8; 4] = b"hhi\0";
pub const PRIiLEAST16: &[u8; 3] = b"hi\0";
pub const PRIiLEAST32: &[u8; 2] = b"i\0";
pub const PRIiLEAST64: &[u8; 4] = b"lli\0";
pub const PRIiFAST8: &[u8; 4] = b"hhi\0";
pub const PRIiFAST16: &[u8; 2] = b"i\0";
pub const PRIiFAST32: &[u8; 2] = b"i\0";
pub const PRIiFAST64: &[u8; 4] = b"lli\0";
pub const PRIiMAX: &[u8; 4] = b"lli\0";
pub const PRIiPTR: &[u8; 4] = b"lli\0";
pub const PRIo8: &[u8; 4] = b"hho\0";
pub const PRIo16: &[u8; 3] = b"ho\0";
pub const PRIo32: &[u8; 2] = b"o\0";
pub const PRIo64: &[u8; 4] = b"llo\0";
pub const PRIoLEAST8: &[u8; 4] = b"hho\0";
pub const PRIoLEAST16: &[u8; 3] = b"ho\0";
pub const PRIoLEAST32: &[u8; 2] = b"o\0";
pub const PRIoLEAST64: &[u8; 4] = b"llo\0";
pub const PRIoFAST8: &[u8; 4] = b"hho\0";
pub const PRIoFAST16: &[u8; 2] = b"o\0";
pub const PRIoFAST32: &[u8; 2] = b"o\0";
pub const PRIoFAST64: &[u8; 4] = b"llo\0";
pub const PRIoMAX: &[u8; 4] = b"llo\0";
pub const PRIoPTR: &[u8; 4] = b"llo\0";
pub const PRIu8: &[u8; 4] = b"hhu\0";
pub const PRIu16: &[u8; 3] = b"hu\0";
pub const PRIu32: &[u8; 2] = b"u\0";
pub const PRIu64: &[u8; 4] = b"llu\0";
pub const PRIuLEAST8: &[u8; 4] = b"hhu\0";
pub const PRIuLEAST16: &[u8; 3] = b"hu\0";
pub const PRIuLEAST32: &[u8; 2] = b"u\0";
pub const PRIuLEAST64: &[u8; 4] = b"llu\0";
pub const PRIuFAST8: &[u8; 4] = b"hhu\0";
pub const PRIuFAST16: &[u8; 2] = b"u\0";
pub const PRIuFAST32: &[u8; 2] = b"u\0";
pub const PRIuFAST64: &[u8; 4] = b"llu\0";
pub const PRIuMAX: &[u8; 4] = b"llu\0";
pub const PRIuPTR: &[u8; 4] = b"llu\0";
pub const PRIx8: &[u8; 4] = b"hhx\0";
pub const PRIx16: &[u8; 3] = b"hx\0";
pub const PRIx32: &[u8; 2] = b"x\0";
pub const PRIx64: &[u8; 4] = b"llx\0";
pub const PRIxLEAST8: &[u8; 4] = b"hhx\0";
pub const PRIxLEAST16: &[u8; 3] = b"hx\0";
pub const PRIxLEAST32: &[u8; 2] = b"x\0";
pub const PRIxLEAST64: &[u8; 4] = b"llx\0";
pub const PRIxFAST8: &[u8; 4] = b"hhx\0";
pub const PRIxFAST16: &[u8; 2] = b"x\0";
pub const PRIxFAST32: &[u8; 2] = b"x\0";
pub const PRIxFAST64: &[u8; 4] = b"llx\0";
pub const PRIxMAX: &[u8; 4] = b"llx\0";
pub const PRIxPTR: &[u8; 4] = b"llx\0";
pub const PRIX8: &[u8; 4] = b"hhX\0";
pub const PRIX16: &[u8; 3] = b"hX\0";
pub const PRIX32: &[u8; 2] = b"X\0";
pub const PRIX64: &[u8; 4] = b"llX\0";
pub const PRIXLEAST8: &[u8; 4] = b"hhX\0";
pub const PRIXLEAST16: &[u8; 3] = b"hX\0";
pub const PRIXLEAST32: &[u8; 2] = b"X\0";
pub const PRIXLEAST64: &[u8; 4] = b"llX\0";
pub const PRIXFAST8: &[u8; 4] = b"hhX\0";
pub const PRIXFAST16: &[u8; 2] = b"X\0";
pub const PRIXFAST32: &[u8; 2] = b"X\0";
pub const PRIXFAST64: &[u8; 4] = b"llX\0";
pub const PRIXMAX: &[u8; 4] = b"llX\0";
pub const PRIXPTR: &[u8; 4] = b"llX\0";
pub const SCNd8: &[u8; 4] = b"hhd\0";
pub const SCNd16: &[u8; 3] = b"hd\0";
pub const SCNd32: &[u8; 2] = b"d\0";
pub const SCNd64: &[u8; 4] = b"lld\0";
pub const SCNdLEAST8: &[u8; 4] = b"hhd\0";
pub const SCNdLEAST16: &[u8; 3] = b"hd\0";
pub const SCNdLEAST32: &[u8; 2] = b"d\0";
pub const SCNdLEAST64: &[u8; 4] = b"lld\0";
pub const SCNdFAST8: &[u8; 4] = b"hhd\0";
pub const SCNdFAST16: &[u8; 2] = b"d\0";
pub const SCNdFAST32: &[u8; 2] = b"d\0";
pub const SCNdFAST64: &[u8; 4] = b"lld\0";
pub const SCNdMAX: &[u8; 4] = b"lld\0";
pub const SCNdPTR: &[u8; 4] = b"lld\0";
pub const SCNi8: &[u8; 4] = b"hhi\0";
pub const SCNi16: &[u8; 3] = b"hi\0";
pub const SCNi32: &[u8; 2] = b"i\0";
pub const SCNi64: &[u8; 4] = b"lli\0";
pub const SCNiLEAST8: &[u8; 4] = b"hhi\0";
pub const SCNiLEAST16: &[u8; 3] = b"hi\0";
pub const SCNiLEAST32: &[u8; 2] = b"i\0";
pub const SCNiLEAST64: &[u8; 4] = b"lli\0";
pub const SCNiFAST8: &[u8; 4] = b"hhi\0";
pub const SCNiFAST16: &[u8; 2] = b"i\0";
pub const SCNiFAST32: &[u8; 2] = b"i\0";
pub const SCNiFAST64: &[u8; 4] = b"lli\0";
pub const SCNiMAX: &[u8; 4] = b"lli\0";
pub const SCNiPTR: &[u8; 4] = b"lli\0";
pub const SCNo8: &[u8; 4] = b"hho\0";
pub const SCNo16: &[u8; 3] = b"ho\0";
pub const SCNo32: &[u8; 2] = b"o\0";
pub const SCNo64: &[u8; 4] = b"llo\0";
pub const SCNoLEAST8: &[u8; 4] = b"hho\0";
pub const SCNoLEAST16: &[u8; 3] = b"ho\0";
pub const SCNoLEAST32: &[u8; 2] = b"o\0";
pub const SCNoLEAST64: &[u8; 4] = b"llo\0";
pub const SCNoFAST8: &[u8; 4] = b"hho\0";
pub const SCNoFAST16: &[u8; 2] = b"o\0";
pub const SCNoFAST32: &[u8; 2] = b"o\0";
pub const SCNoFAST64: &[u8; 4] = b"llo\0";
pub const SCNoMAX: &[u8; 4] = b"llo\0";
pub const SCNoPTR: &[u8; 4] = b"llo\0";
pub const SCNu8: &[u8; 4] = b"hhu\0";
pub const SCNu16: &[u8; 3] = b"hu\0";
pub const SCNu32: &[u8; 2] = b"u\0";
pub const SCNu64: &[u8; 4] = b"llu\0";
pub const SCNuLEAST8: &[u8; 4] = b"hhu\0";
pub const SCNuLEAST16: &[u8; 3] = b"hu\0";
pub const SCNuLEAST32: &[u8; 2] = b"u\0";
pub const SCNuLEAST64: &[u8; 4] = b"llu\0";
pub const SCNuFAST8: &[u8; 4] = b"hhu\0";
pub const SCNuFAST16: &[u8; 2] = b"u\0";
pub const SCNuFAST32: &[u8; 2] = b"u\0";
pub const SCNuFAST64: &[u8; 4] = b"llu\0";
pub const SCNuMAX: &[u8; 4] = b"llu\0";
pub const SCNuPTR: &[u8; 4] = b"llu\0";
pub const SCNx8: &[u8; 4] = b"hhx\0";
pub const SCNx16: &[u8; 3] = b"hx\0";
pub const SCNx32: &[u8; 2] = b"x\0";
pub const SCNx64: &[u8; 4] = b"llx\0";
pub const SCNxLEAST8: &[u8; 4] = b"hhx\0";
pub const SCNxLEAST16: &[u8; 3] = b"hx\0";
pub const SCNxLEAST32: &[u8; 2] = b"x\0";
pub const SCNxLEAST64: &[u8; 4] = b"llx\0";
pub const SCNxFAST8: &[u8; 4] = b"hhx\0";
pub const SCNxFAST16: &[u8; 2] = b"x\0";
pub const SCNxFAST32: &[u8; 2] = b"x\0";
pub const SCNxFAST64: &[u8; 4] = b"llx\0";
pub const SCNxMAX: &[u8; 4] = b"llx\0";
pub const SCNxPTR: &[u8; 4] = b"llx\0";
pub type va_list = *mut ::std::os::raw::c_char;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type __crt_bool = bool;
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo();
}
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn() -> !;
}
unsafe extern "C" {
    pub fn _invoke_watson(
        _Expression: *const wchar_t,
        _FunctionName: *const wchar_t,
        _FileName: *const wchar_t,
        _LineNo: ::std::os::raw::c_uint,
        _Reserved: usize,
    ) -> !;
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_data_public"]
        [::std::mem::size_of::<__crt_locale_data_public>() - 16usize];
    ["Alignment of __crt_locale_data_public"]
        [::std::mem::align_of::<__crt_locale_data_public>() - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_pctype"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_pctype) - 0usize];
    ["Offset of field: __crt_locale_data_public::_locale_mb_cur_max"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_mb_cur_max) - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_lc_codepage"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_lc_codepage) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_pointers"][::std::mem::size_of::<__crt_locale_pointers>() - 16usize];
    ["Alignment of __crt_locale_pointers"]
        [::std::mem::align_of::<__crt_locale_pointers>() - 8usize];
    ["Offset of field: __crt_locale_pointers::locinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, locinfo) - 0usize];
    ["Offset of field: __crt_locale_pointers::mbcinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, mbcinfo) - 8usize];
};
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Mbstatet"][::std::mem::size_of::<_Mbstatet>() - 8usize];
    ["Alignment of _Mbstatet"][::std::mem::align_of::<_Mbstatet>() - 4usize];
    ["Offset of field: _Mbstatet::_Wchar"][::std::mem::offset_of!(_Mbstatet, _Wchar) - 0usize];
    ["Offset of field: _Mbstatet::_Byte"][::std::mem::offset_of!(_Mbstatet, _Byte) - 4usize];
    ["Offset of field: _Mbstatet::_State"][::std::mem::offset_of!(_Mbstatet, _State) - 6usize];
};
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = usize;
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Lldiv_t {
    pub quot: intmax_t,
    pub rem: intmax_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Lldiv_t"][::std::mem::size_of::<_Lldiv_t>() - 16usize];
    ["Alignment of _Lldiv_t"][::std::mem::align_of::<_Lldiv_t>() - 8usize];
    ["Offset of field: _Lldiv_t::quot"][::std::mem::offset_of!(_Lldiv_t, quot) - 0usize];
    ["Offset of field: _Lldiv_t::rem"][::std::mem::offset_of!(_Lldiv_t, rem) - 8usize];
};
pub type imaxdiv_t = _Lldiv_t;
unsafe extern "C" {
    pub fn imaxabs(_Number: intmax_t) -> intmax_t;
}
unsafe extern "C" {
    pub fn imaxdiv(_Numerator: intmax_t, _Denominator: intmax_t) -> imaxdiv_t;
}
unsafe extern "C" {
    pub fn strtoimax(
        _String: *const ::std::os::raw::c_char,
        _EndPtr: *mut *mut ::std::os::raw::c_char,
        _Radix: ::std::os::raw::c_int,
    ) -> intmax_t;
}
unsafe extern "C" {
    pub fn _strtoimax_l(
        _String: *const ::std::os::raw::c_char,
        _EndPtr: *mut *mut ::std::os::raw::c_char,
        _Radix: ::std::os::raw::c_int,
        _Locale: _locale_t,
    ) -> intmax_t;
}
unsafe extern "C" {
    pub fn strtoumax(
        _String: *const ::std::os::raw::c_char,
        _EndPtr: *mut *mut ::std::os::raw::c_char,
        _Radix: ::std::os::raw::c_int,
    ) -> uintmax_t;
}
unsafe extern "C" {
    pub fn _strtoumax_l(
        _String: *const ::std::os::raw::c_char,
        _EndPtr: *mut *mut ::std::os::raw::c_char,
        _Radix: ::std::os::raw::c_int,
        _Locale: _locale_t,
    ) -> uintmax_t;
}
unsafe extern "C" {
    pub fn wcstoimax(
        _String: *const wchar_t,
        _EndPtr: *mut *mut wchar_t,
        _Radix: ::std::os::raw::c_int,
    ) -> intmax_t;
}
unsafe extern "C" {
    pub fn _wcstoimax_l(
        _String: *const wchar_t,
        _EndPtr: *mut *mut wchar_t,
        _Radix: ::std::os::raw::c_int,
        _Locale: _locale_t,
    ) -> intmax_t;
}
unsafe extern "C" {
    pub fn wcstoumax(
        _String: *const wchar_t,
        _EndPtr: *mut *mut wchar_t,
        _Radix: ::std::os::raw::c_int,
    ) -> uintmax_t;
}
unsafe extern "C" {
    pub fn _wcstoumax_l(
        _String: *const wchar_t,
        _EndPtr: *mut *mut wchar_t,
        _Radix: ::std::os::raw::c_int,
        _Locale: _locale_t,
    ) -> uintmax_t;
}
pub const HANGUL_CHOSEONG_FILLER: _bindgen_ty_1 = 4447;
pub const HANGUL_JUNGSEONG_FILLER: _bindgen_ty_1 = 4448;
pub type _bindgen_ty_1 = ::std::os::raw::c_int;
pub type ucschar = u32;
unsafe extern "C" {
    pub fn hangul_is_choseong(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jungseong(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jongseong(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_choseong_conjoinable(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jungseong_conjoinable(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jongseong_conjoinable(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jamo_conjoinable(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_syllable(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_jamo(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_is_cjamo(c: ucschar) -> bool;
}
unsafe extern "C" {
    pub fn hangul_jamo_to_cjamo(ch: ucschar) -> ucschar;
}
unsafe extern "C" {
    pub fn hangul_syllable_iterator_prev(
        str_: *const ucschar,
        begin: *const ucschar,
    ) -> *const ucschar;
}
unsafe extern "C" {
    pub fn hangul_syllable_iterator_next(
        str_: *const ucschar,
        end: *const ucschar,
    ) -> *const ucschar;
}
unsafe extern "C" {
    pub fn hangul_syllable_len(
        str_: *const ucschar,
        max_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn hangul_jamo_to_syllable(
        choseong: ucschar,
        jungseong: ucschar,
        jongseong: ucschar,
    ) -> ucschar;
}
unsafe extern "C" {
    pub fn hangul_syllable_to_jamo(
        syllable: ucschar,
        choseong: *mut ucschar,
        jungseong: *mut ucschar,
        jongseong: *mut ucschar,
    );
}
unsafe extern "C" {
    pub fn hangul_jamos_to_syllables(
        dest: *mut ucschar,
        destlen: ::std::os::raw::c_int,
        src: *const ucschar,
        srclen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HangulKeyboard {
    _unused: [u8; 0],
}
pub type HangulKeyboard = _HangulKeyboard;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HangulCombination {
    _unused: [u8; 0],
}
pub type HangulCombination = _HangulCombination;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HangulBuffer {
    _unused: [u8; 0],
}
pub type HangulBuffer = _HangulBuffer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HangulInputContext {
    _unused: [u8; 0],
}
pub type HangulInputContext = _HangulInputContext;
pub const HANGUL_OUTPUT_SYLLABLE: _bindgen_ty_2 = 0;
pub const HANGUL_OUTPUT_JAMO: _bindgen_ty_2 = 1;
pub type _bindgen_ty_2 = ::std::os::raw::c_int;
pub const HANGUL_KEYBOARD_TYPE_JAMO: _bindgen_ty_3 = 0;
pub const HANGUL_KEYBOARD_TYPE_JASO: _bindgen_ty_3 = 1;
pub const HANGUL_KEYBOARD_TYPE_ROMAJA: _bindgen_ty_3 = 2;
pub const HANGUL_KEYBOARD_TYPE_JAMO_YET: _bindgen_ty_3 = 3;
pub const HANGUL_KEYBOARD_TYPE_JASO_YET: _bindgen_ty_3 = 4;
pub type _bindgen_ty_3 = ::std::os::raw::c_int;
pub const HANGUL_IC_OPTION_AUTO_REORDER: _bindgen_ty_4 = 0;
pub const HANGUL_IC_OPTION_COMBI_ON_DOUBLE_STROKE: _bindgen_ty_4 = 1;
pub const HANGUL_IC_OPTION_NON_CHOSEONG_COMBI: _bindgen_ty_4 = 2;
pub type _bindgen_ty_4 = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn hangul_keyboard_new() -> *mut HangulKeyboard;
}
unsafe extern "C" {
    pub fn hangul_keyboard_new_from_file(
        path: *const ::std::os::raw::c_char,
    ) -> *mut HangulKeyboard;
}
unsafe extern "C" {
    pub fn hangul_keyboard_delete(keyboard: *mut HangulKeyboard);
}
unsafe extern "C" {
    pub fn hangul_keyboard_set_type(keyboard: *mut HangulKeyboard, type_: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_get_count() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_get_keyboard_id(
        index_: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_get_keyboard_name(
        index_: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_get_keyboard(
        id: *const ::std::os::raw::c_char,
    ) -> *const HangulKeyboard;
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_register_keyboard(
        keyboard: *mut HangulKeyboard,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hangul_keyboard_list_unregister_keyboard(
        id: *const ::std::os::raw::c_char,
    ) -> *mut HangulKeyboard;
}
unsafe extern "C" {
    pub fn hangul_combination_new() -> *mut HangulCombination;
}
unsafe extern "C" {
    pub fn hangul_combination_delete(combination: *mut HangulCombination);
}
unsafe extern "C" {
    pub fn hangul_combination_set_data(
        combination: *mut HangulCombination,
        first: *mut ucschar,
        second: *mut ucschar,
        result: *mut ucschar,
        n: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_new(keyboard: *const ::std::os::raw::c_char) -> *mut HangulInputContext;
}
unsafe extern "C" {
    pub fn hangul_ic_delete(hic: *mut HangulInputContext);
}
unsafe extern "C" {
    pub fn hangul_ic_process(hic: *mut HangulInputContext, ascii: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_reset(hic: *mut HangulInputContext);
}
unsafe extern "C" {
    pub fn hangul_ic_backspace(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_is_empty(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_has_choseong(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_has_jungseong(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_has_jongseong(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_is_transliteration(hic: *mut HangulInputContext) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_get_option(
        hic: *mut HangulInputContext,
        option: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn hangul_ic_set_option(
        hic: *mut HangulInputContext,
        option: ::std::os::raw::c_int,
        value: bool,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_set_output_mode(hic: *mut HangulInputContext, mode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn hangul_ic_set_keyboard(hic: *mut HangulInputContext, keyboard: *const HangulKeyboard);
}
unsafe extern "C" {
    pub fn hangul_ic_switch_keyboard_table(
        hic: *mut HangulInputContext,
        tableid: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_select_keyboard(
        hic: *mut HangulInputContext,
        id: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_connect_callback(
        hic: *mut HangulInputContext,
        event: *const ::std::os::raw::c_char,
        callback: *mut ::std::os::raw::c_void,
        user_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_get_preedit_string(hic: *mut HangulInputContext) -> *const ucschar;
}
unsafe extern "C" {
    pub fn hangul_ic_get_commit_string(hic: *mut HangulInputContext) -> *const ucschar;
}
unsafe extern "C" {
    pub fn hangul_ic_flush(hic: *mut HangulInputContext) -> *const ucschar;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Hanja {
    _unused: [u8; 0],
}
pub type Hanja = _Hanja;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HanjaList {
    _unused: [u8; 0],
}
pub type HanjaList = _HanjaList;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HanjaTable {
    _unused: [u8; 0],
}
pub type HanjaTable = _HanjaTable;
unsafe extern "C" {
    pub fn hanja_table_load(filename: *const ::std::os::raw::c_char) -> *mut HanjaTable;
}
unsafe extern "C" {
    pub fn hanja_table_match_exact(
        table: *const HanjaTable,
        key: *const ::std::os::raw::c_char,
    ) -> *mut HanjaList;
}
unsafe extern "C" {
    pub fn hanja_table_match_prefix(
        table: *const HanjaTable,
        key: *const ::std::os::raw::c_char,
    ) -> *mut HanjaList;
}
unsafe extern "C" {
    pub fn hanja_table_match_suffix(
        table: *const HanjaTable,
        key: *const ::std::os::raw::c_char,
    ) -> *mut HanjaList;
}
unsafe extern "C" {
    pub fn hanja_table_delete(table: *mut HanjaTable);
}
unsafe extern "C" {
    pub fn hanja_list_get_size(list: *const HanjaList) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn hanja_list_get_key(list: *const HanjaList) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_list_get_nth(list: *const HanjaList, n: ::std::os::raw::c_uint) -> *const Hanja;
}
unsafe extern "C" {
    pub fn hanja_list_get_nth_key(
        list: *const HanjaList,
        n: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_list_get_nth_value(
        list: *const HanjaList,
        n: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_list_get_nth_comment(
        list: *const HanjaList,
        n: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_list_delete(list: *mut HanjaList);
}
unsafe extern "C" {
    pub fn hanja_get_key(hanja: *const Hanja) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_get_value(hanja: *const Hanja) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hanja_get_comment(hanja: *const Hanja) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hangul_keyboard_set_value(
        keyboard: *mut HangulKeyboard,
        key: ::std::os::raw::c_int,
        value: ucschar,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_set_combination(
        hic: *mut HangulInputContext,
        combination: *const HangulCombination,
    );
}
unsafe extern "C" {
    pub fn hangul_ic_get_n_keyboards() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn hangul_ic_get_keyboard_id(
        index_: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hangul_ic_get_keyboard_name(
        index_: ::std::os::raw::c_uint,
    ) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8,
}
